name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "First Issue report, Wohooo ! Welcome onboard, this issue will be hunted down soon !!"
        pr-message: "First Pull request ! U no longer an open source virgin !!"
